local modelsToHighlight = {
    "Noobini Pizzanini",
    "Liril\xEC Laril\xE0",
    "Tim Cheese",
    "Fluriflura",
    "Svinina Bombardino",
    "Talpa Di Fero",
    "Pipi Kiwi",
    "Pipi Corni",
    "Raccooni Jandelini",
    "Trippi Troppi",
    "Gangster Footera",
    "Boneca Ambalabu",
    "Ta Ta Ta Ta Sahur",
    "Tric Trac Baraboom",
    "Bandito Bobritto",
    "Cacto Hipopotamo",
    "Pipi Avocado",
    "Cappuccino Assassino",
    "Brr Brr Patapim",
    "Trulimero Trulicina",
    "Bananita Dolphinita",
    "Brri Brri Bicus Dicus Bombicus",
    "Bambini Crostini",
    "Perochello Lemonchello",
    "Avocadini Guffo",
    "Salamino Penguino",
    "Ti Ti Ti Sahur",
    "Penguino Cocosino",
    "Avocadini Antilopini",
    "Bandito Axolito",
    "Malame Amarele",
    "Mangolini Parrocini",
    "Burbaloni Loliloli",
    "Chimpanzini Bananini",
    "Ballerina Cappuccina",
    "Chef Crabracadabra",
    "Glorbo Fruttodrillo",
    "Blueberrinni Octopusini",
    "Lionel Cactuseli",
    "Pandaccini Bananini",
    "Strawberrelli Flamingelli",
    "Cocosini Mama",
    "Pi Pi Watermelon",
    "Sigma Boy",
    "Pipi Potato",
    "Quivioli Ameleonni",
    "Tirilikalika Tirilikalako",
    "Caramello Filtrello",
    "Signore Carapace",
    "Frigo Camelo",
    "Orangutini Ananassini",
    "Bombardiro Crocodilo",
    "Bombombini Gusini",
    "Rhino Toasterino",
    "Cavallo Virtuoso",
    "Spioniro Golubiro",
    "Zibra Zubra Zibralini",
    "Tigrilini Watermelini",
    "Gorillo Watermelondrillo",
    "Avocadorilla",
    "Ganganzelli Trulala",
    "Tob Tobi Tobi",
    "Te Te Te Sahur",
    "Tracoducotulu Delapeladustuz",
    "Lerulerulerule",
    "Carloo",
    "Carrotini Brainini",
    "Brutto Gialutto",
    "Gorillo Subwoofero",
    "Los Noobinis",
    "Rhino Helicopterino",
    "Chihuanini Taconini",
    "Cocofanto Elefanto",
    "Tralalero Tralala",
    "Odin Din Din Dun",
    "Girafa Celestre",
    "Trenostruzzo Turbo 3000",
    "Matteo",
    "Tigroligre Frutonni",
    "Orcalero Orcala",
    "Unclito Samito",
    "Gattatino Nyanino",
    "Espresso Signora",
    "Ballerino Lololo",
    "Piccione Macchina",
    "Los Crocodillitos",
    "Tukanno Bananno",
    "Trippi Troppi Troppa Trippa",
    "Los Tungtungtungcitos",
    "Agarrini la Palini",
    "Bulbito Bandito Traktorito",
    "Los Orcalitos",
    "Tipi Topi Taco",
    "Bombardini Tortinii",
    "Tralalita Tralala",
    "Urubini Flamenguini",
    "Alessio",
    "Pakrahmatmamat",
    "Los Bombinitos",
    "Brr es Teh Patipum",
    "Tartaruga Cisterna",
    "Cacasito Satalito",
    "Mastodontico Telepiedone",
    "Crabbo Limonetta",
    "Gattito Tacoto",
    "Los Tipi Tacos",
    "Antonio",
    "Las Capuchinas",
    "Orcalita Orcala",
    "Piccionetta Macchina",
    "Anpali Babel",
    "Extinct Ballerina",
    "Tractoro Dinosauro",
    "Belula Beluga",
    "La Vacca Saturno Saturnita",
    "Los Tralaleritos",
    "Graipuss Medussi",
    "La Grande Combinasion",
    "Sammyni Spyderini",
    "Garama and Madundung",
    "Torrtuginni Dragonfrutini",
    "Las Tralaleritas",
    "Pot Hotspot",
    "Nuclearo Dinossauro",
    "Las Vaquitas Saturnitas",
    "Chicleteira Bicicleteira",
    "Agarrini la Palini",
    "Los Combinasionas",
    "Karkerkar Kurkur",
    "Dragon Cannelloni",
    "Los Hotspotsitos",
    "Esok Sekolah",
    "Nooo My Hotspot",
    "Los Matteos",
    "Job Job Job Sahur",
    "Dul Dul Dul",
    "Blackhole Goat",
    "Los Spyderinis",
    "Ketupat Kepat",
    "La Supreme Combinasion",
    "Bisonte Giuppitere",
    "Guerriro Digitale",
    "Ketchuru and Musturu",
    "Spaghetti Tualetti",
    "Los Nooo My Hotspotsitos",
    "Trenostruzzo Turbo 4000",
    "Fragola La La La",
    "La Sahur Combinasion",
    "La Karkerkar Combinasion",
    "Tralaledon",
    "Los Bros",
    "Los Chicleteiras",
    "Chachechi",
    "Extinct Tralalero",
    "Extinct Matteo",
    "67",
    "Las Sis",
    "Celularcini Viciosini",
    "La Extinct Grande",
    "Strawberry Elephant",
    "Mythic Lucky Block",
    "Brainrot God Lucky Block",
    "Secret Lucky Block",
    "Admin Lucky Block",
    "Taco Lucky Block"
}

local highlights = {}

local function createHighlight(model)
    local highlight = Instance.new("BoxHandleAdornment")
    highlight.Adornee = model
    highlight.AlwaysOnTop = true
    highlight.ZIndex = 0
    highlight.Size = model:GetExtentsSize()
    highlight.Color3 = Color3.fromRGB(255, 0, 0)
    highlight.Transparency = 0.5
    highlight.Parent = game:GetService("CoreGui")
    highlights[model] = highlight
end

local function findAndHighlightModels()
    local plots = workspace:FindFirstChild("Plots")
    if not plots then return end

    for _, plot in pairs(plots:GetChildren()) do
        for _, modelName in pairs(modelsToHighlight) do
            local model = plot:FindFirstChild(modelName)
            if model and model:IsA("Model") and not highlights[model] then
                createHighlight(model)
            end
        end
    end
end

-- Основной цикл
while true do
    findAndHighlightModels()
    task.wait(1)
end
